### ISSUE TITLE
Conditional import for z3 dependency in transforms.py

### ISSUE THREAD

**Issue by TheGreatCorrine** [pyta-uoft/pyta#1117]
Under python_ta/patches/transforms.py

In the `transforms.py` file, the import of Z3Visitor should be conditional. 
If the user has not installed the z3 dependency, the import should be handled gracefully using a `try-except` block. This will prevent errors when the z3 dependency is not available.

[Error image]
![image](https://github.com/user-attachments/assets/4c6058cc-892b-41f6-b381-fe6b01e53b88)

**Comment by david-yz-liu** [comment]
Thank you @TheGreatCorrine, this has been fixed!
