### ISSUE TITLE
tokenize, JSON, _display

### ISSUE THREAD

**Issue by rebeccakay** [pyta-uoft/pyta#133]
- [ ] tokenize.generate_tokens seems to only be used in python2 according to docs.python.org and new version is supposed to be tokenize.tokenize? However changing it to new version seems to create an error "startswith first arg must be str or a tuple of str, not bytes". Looking at past pull requests though, it seems like there is a possible plan to remove it altogether.
- [ ]  pylint replaced html_reporter with json_reporter because it's "prettier" 
- [x] set _display to None

**Comment by nigef** [comment]
Hi @rebeccakay, what action item is the second checkbox referring to do?
