### ISSUE TITLE
Highlighting for trailing-newlines needs improvement

### ISSUE THREAD

**Issue by IskyN** [pyta-uoft/pyta#153]
As of PR #151, ColorReporter and HTMLReporter, when encountering a `trailing-newlines` style error, highlight the number of the line on which the error was made, and provide surrounding context lines in grey as usual. However, as per @david-yz-liu's suggestion, the reporters should show/highlight "*all* the trailing newlines (including the last one) to make it more obvious what the problem is." 

There are two problems with this proposition:
1. It seems that the Python `readlines` method automatically omits an end-of-file newline if there is one, so that in a file with 2 trailing newlines, the `_source_lines` will only have 1 stored; in a file with 3 trailing newlines, there will be 2 in `_source_lines`; and so on. 
_Possible workaround:_ assume there is always 1 more trailing newline than reported, and go from there.
2. In a file with more than 2 trailing newlines (so more than 1 extra), the checker finding trailing-newlines errors only identifies the last newline (really the second-last, see problem 1) as erroneous. Thus, highlighting _all_ extraneous newlines is not feasible at the reporter level. This seems to be a fix better suited to a checker or patch.

**Comment by david-yz-liu** [comment]
We now display all trailing newlines that should be deleted.
