### ISSUE TITLE
Create `checkers` subdirectory and put all checkers there

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#17]
All checker classes should be in their own file in this new subdirectory.

As an addition, the sample `MyCustomChecker` class should be renamed.

**Comment by david-yz-liu** [comment]
@hayleyZHL since you asked, I'm going to assign this one to you.

**Comment by hayleyZHL** [comment]
Created subdirectory checkers and put dynamic_execution_checker and forbidden_import_checker(originally sample checker) in pull request [https://github.com/pyta-uoft/pyta/pull/26](url)
