### ISSUE TITLE
Pylint Exploration

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#2]
We are using pylint, which does a lot of static analysis already. However, we want to do three things: 
1. Decide which errors to check for and which to ignore entirely.
2. Of the errors that we allow pylint to report, identify and set any configuration options used (in `.pylintrc`)
3. Provide better documentation (including examples) for _every_ error message a student will see. I have provided such examples for the `elif` checker in #1. These examples must also be added to the website, along with more descriptive documentation.

You can find the pylint documentation of its checkers here: https://docs.pylint.org/features.html#pylint-checkers-options-and-switches. 

You may also need to consult the source code, which can be found here: https://github.com/PyCQA/pylint/tree/master/pylint/checkers.

Here's a list of the different checkers:
- [x] `elif` @david-yz-liu
- [x] `multiple_types` @nigef 
- [x] `imports` @nigef 
- [x] `variables` @hayleyZHL 
- [x] `design` @nigef 
- [x] `stdlib` @nigef 
- [x] `similarities` @Jasminewwwu -- disable
- [x] `basic` @shweta97 
- [x] `newstyle` @Jasminewwwu -- disable
- [x] `iterable_check` @shweta97
- [x] `string` @Jasminewwwu 
- [x] `format` @shweta97 
- [x] `miscellaneous` @hayleyZHL -- (disable W0512 but keep W0511)
- [x] `metrics` @david-yz-liu (no checks?)
- [x] `spelling` @hayleyZHL -- disable
- [x] `python3` @Jasminewwwu -- disable
- [x] `logging` @hayleyZHL 
- [x] `typecheck` @Jasminewwwu 
- [x] `classes` @WChrisK
- [x] `string_constant` @Jasminewwwu
- [x] `exceptions` @WChrisK
- [x] `async` @hayleyZHL -- disable

**Comment by WChrisK** [comment]
Ignoring the following, but requesting a look over for corner cases I'm unsure about:

**bad-exception-context (E0703)** -  Only works for Python versions under 3.0, and since we will require students to use 3.3+, this can't be found

**notimplemented-raised (E0711):** - I can't imagine students using this, can you? Or do you want it for completion?

**Comment by Jasminewwwu** [comment]
anomalous-unicode-escape-in-string(W1402).
missing-kwoa(E1125) 
not-context-manager(E1129) 
I think csc148 students will not encounter these errors...
what do u think?

**Comment by david-yz-liu** [comment]
**bad-exception-context (E0703)** - Indeed, we will omit all errors which can't be emitted in Python < 3.

**notimplemented-raised (E0711)** - We do talk about `NotImplementedError` in CSC148, so we should keep this one just in case students get it wrong. (But in general I don't want to include errors just for the sake of completeness.)

**anomalous-unicode-escape-in-string (W1402)** - It's fine to ignore this one. We don't really talk about Unicode.

**missing-kwoa(E1125) ** - see above comment about Python 3.

**not-context-manager(E1129) ** - students *might* see a lab with this, so I'd prefer to keep this one in.

**Comment by shweta97** [comment]
continue-in-finally(E0116) - I don't think this is required as we don't use the finally clause in CSC148
errors with star assignments, yield statements, lambda and generators - also not required as we are not taught any of them in CSC108 and CSC148
Any thoughts? Do you think its ok to leave these out?

**Comment by david-yz-liu** [comment]
@shweta97 I agree, you can leave that one out.

**Comment by Jasminewwwu** [comment]
repeated-keyword (E1132): should we keep this since csc108 & csc148 students mostly occur redundant-keyword-arg (E1124) and duplicate-argument-name error...

**Comment by WChrisK** [comment]
Should this be covered?

non-iterator-returned (E0301):
 	__iter__ returns non-iterator Used when an __iter__ method returns something which is not an iterable (i.e. has no next method)

I don't know if 148 covers these

**Comment by david-yz-liu** [comment]
Omit the ones about `__slots__`. You can omit the E0301 too.

**Comment by nigef** [comment]
some examples in the `variables` checker do not return the intended messages:

E0633_unpacking_non_sequence,
E0611_no_name_in_module,
