### ISSUE TITLE
.pylintrc should not contain line breaks in the disable value

### ISSUE THREAD

**Issue by nigef** [pyta-uoft/pyta#25]
I propose we should let this value run over 80 characters.

**Comment by shweta97** [comment]
Just curious, why do you say so?

**Comment by nigef** [comment]
I get a `ParsingError` of the `.pylintrc`

**Comment by shweta97** [comment]
Oh I see. Then it makes sense to have all the disable statements in one line.

**Comment by david-yz-liu** [comment]
Thanks for pointing this out, @nigef! I have fixed the syntax error - it is possible to have multi-line values,
as long as continued lines are indented.

Took a bit of research to find the proper documentation: https://docs.python.org/3/library/configparser.html

**Comment by nigef** [comment]
that makes sense; subtle
