### ISSUE TITLE
Unable to parse complex PEP526 type annotations

### ISSUE THREAD

**Issue by RonnChyran** [pyta-uoft/pyta#315]
Take for example this valid type-annotated Python 3.6 code for a list that contains tuples with named members.
```python
 id_: str
 car: Car
 eligible_cars: List[Tuple[id_: str, car: Car]] = [ ... ]
```

This throws E1127 (invalid-slice-index) when run with PyTA.

**Comment by david-yz-liu** [comment]
Hi @RonnChyran! Naming elements of tuples is not supported by the `typing` module; this is not an issue with PyTA, but instead an improper use of `Tuple` type annotations.
