### ISSUE TITLE
Check for always returning in a loop

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#32]
A common student error is to always return inside a loop body, which causes the loop to only ever excute once:

```python
def all_pos(lst):
    for num in lst:
       if num > 0:
           return True
       else:
           return False
```

pylint will pick up on the return True/return False simplification (ask @shweta97 for details), but it won't pick up on the fact that the loop only runs once. We should really check this, as it happens all the time!

**Comment by david-yz-liu** [comment]
@Jasminewwwu I'm giving you this one, which is more challenging and will take some time, but a good experience.

As a first step, you should define a recursive function which takes a node and determines whether that node represents a sequence of operations that *always* has an explicit return instruction. Here are some cases:

1. If the node is just a single statement, check whether it's a return statement.
2. If it's a sequence of statements, check whether one of them is a return statement.
3. If it's an if statement, check *each branch* separately, and only return True if *every* branch has an explicit return.
4. If it's a loop, check the body of the loop.

Note: ignore all other types of statements for now. This can be done using a recursive algorithm, if you understand the different node attributes.

**Comment by Jasminewwwu** [comment]
@shweta97 Could you please explain me about the "pylint will pick up on the return True/return False simplification"? Thanks!

**Comment by shweta97** [comment]
@Jasminewwwu I'm sorry but I haven't come across that but yet so I'm not sure how pylint picks up on that. Will let u know if I come across this.
