### ISSUE TITLE
Investigate documentation checking

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#35]
One big goal is to analyse docstrings that students write for their modules, classes, and functions. However, it seems like the AST parsing that `ast` and `astroid` perform do not expose docstrings, so we can't access them through the AST. (Am I wrong? Would be nice to find out.)

However, pylint does seem to check something about docstrings (e.g., there one error it checks is "missing docstring"). How does it do it, and how can we build on it?

Probably good to investigate the `DocstringChecker` class defined here:
https://github.com/PyCQA/pylint/blob/master/pylint/checkers/base.py#L1319

@WChrisK I'm giving you this one since it may or may not be a bit involved.

**Comment by WChrisK** [comment]
- For the ones that belong to functions or methods, should be able to parse it according to the 108 recipe design format (find this on the 108 website, search 'csc108 function design recipe')

Don't use regex
