### ISSUE TITLE
SyntaxErro while importing python_ta

### ISSUE THREAD

**Issue by mzfr** [pyta-uoft/pyta#374]
I installed pyta with`pip3 install python_ta` and installation was successful. But when I am trying `import python_ta` I am getting a traceback error:
```traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/python_ta/__init__.py", line 37, in <module>
    from .patches import patch_all
  File "/usr/local/lib/python3.5/dist-packages/python_ta/patches/__init__.py", line 4, in <module>
    from .type import patch_type_inference_transform
  File "/usr/local/lib/python3.5/dist-packages/python_ta/patches/type.py", line 4, in <module>
    from ..transforms.type_inference_visitor import TypeInferer
  File "/usr/local/lib/python3.5/dist-packages/python_ta/transforms/type_inference_visitor.py", line 118
    if hasattr(self, f'visit_{klass.__name__.lower()}'):
                                                     ^
SyntaxError: invalid syntax
invalid syntax (type_inference_visitor.py, line 118)
```

**Comment by acbart** [comment]
Hi, I'm not affiliated with the project, but I can explain what happened here. Their code uses [f-strings](https://www.python.org/dev/peps/pep-0498/), a new feature in Python 3.6. You're using Python 3.5, which means you cannot use that syntactic feature. You'll just need to upgrade your Python 3 version.

For the developers, you might want to consider whether they should use this awesome new language feature in place of `.format()`; not everyone's willing to upgrade their servers, unfortunately.

**Comment by david-yz-liu** [comment]
Hi @mzfr, thanks for reporting this issue. Unfortunately right now we do only support Python 3.6+. 

@acbart I'm definitely open to not using this language feature and to change this in the future, but unfortunately don't have the time to do so right now. I'll update the README and setup.py to specify this for now, though. Thanks for your comment!
