### ISSUE TITLE
Automatically embed code examples into website

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#4]
All code examples in `examples/` should be embedded in corresponding error sections in the pyta-website.

The simplest approach would be to be able to reference external code in the website markdown, and have it be resolved by pandoc when the website actually gets generated. I'm not sure if that's actually possible, though.

**Comment by nigef** [comment]
Followup -- we were able to use the python package, [pandocfilters](https://github.com/jgm/pandocfilters#pandocfilters) to resolve this.
