### ISSUE TITLE
Improve robustness of module loading

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#45]
Right now, if a user types in a module name which is missing, or which has the extension `.py`, the checker will fail. Two changes should be made:

1. Detect if the extension `.py` is added, and if it is, remove it but load the correct module without error.
2. Catch the correct exception when a module is not found, and report a good error message to the user.

**Comment by hayleyZHL** [comment]
One thing I'm not sure of: If a user types in module name without `""`, or the user input the wrong type as the module name, for example, `pyta.check(3)`, should we rewrite the error message as well? Or it's their responsibility to know the right parameter type?

**Comment by nigef** [comment]
for those two examples, i think something more generic is fine, like 'module <what_they_entered> not found'... we don't need to tell them explicitly that the type is wrong.

**Comment by hayleyZHL** [comment]
They are different things, if the type is wrong, then it is a completely different error occurred right at the beginning of pyta.py, with different type of exceptions.

**Comment by nigef** [comment]
We can make that distinction, although it may not be necessary, anyways it sounds like you have it figured out 👍
