### ISSUE TITLE
Detect parsing errors on import

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#53]
Currently, if a Python source file has a syntax error and cannot be parsed, PyTA crashes when it tries to import the file.

Instead, it should catch the exception, and print a useful message to the user which is as detailed as possible (certainly better than the default Python message that comes with the error). Of course, common syntax errors should also be documented properly on the website.

**Comment by Jasminewwwu** [comment]
I ran pyta on some source file which has a syntax error. And it shows something like this in the module.
E0001: (syntax-error)
    Missing parentheses in call to 'print'

Should I overwrite something to replace this?

**Comment by david-yz-liu** [comment]
@Jasminewwwu Yeah, please make this more descriptive (for beginners).
