### ISSUE TITLE
Set node ending attributes

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/pyta#60]
We would like to augment the existing astroid AST so that the attributes `end_lineno` and `end_col_offset` store the line and column offset where the node ends.

@Jasminewwwu suggested to use some combination of the existing `lineno` and `col_offset` attributes, together with a proper tree traversal (`next_sibling`?) as a first approximation of these attributes. That seems like an excellent place to start.

**Comment by nigef** [comment]
Actually I suggested that last week. Will do!
