### ISSUE TITLE
C0303 (trailing-whitespace) Line Number Error after doctest

### ISSUE THREAD

**Issue by MichaelLiut** [pyta-uoft/pyta#648]
It appears that in some cases a C0303 (trailing-whitespace) will occur on the first line of a doctest even if the trailing white space occurs at the end of the doctest. 

For example: 
```
  1. def foo(a: int) -> boolean:
  2.    """ Some description of foo.
  3.
  4.    >>> foo(30)
  5.    True
  6.    >>> foo(45)
  7.    False
  8.        
  9.    """
```

Where the whitespace occurs on line 8 but will report itself on line 4.

**Comment by MichaelLiut** [comment]
**`boolean` should read `bool`

**Comment by ckatsube** [comment]
It may have been an issue back then, but it doesn't appear to be one now. Both python_ta and pylint recognize that the trailing whitespace is on line 8, not line 4.

Python_ta output
![image](https://user-images.githubusercontent.com/13248104/122161383-9dc30f80-ce3f-11eb-9128-14077bdec9f6.png)
Pylint output
```
sandbox.py:8:0: C0303: Trailing whitespace (trailing-whitespace)
sandbox.py:1:0: C0114: Missing module docstring (missing-module-docstring)
sandbox.py:1:0: C0104: Disallowed name "foo" (disallowed-name)
sandbox.py:1:0: C0103: Argument name "a" doesn't conform to snake_case naming style (invalid-name)
sandbox.py:1:8: W0613: Unused argument 'a' (unused-argument)
```

**Comment by ckatsube** [comment]
Brief note: upon revising this I realize that this is still a bug in the latest 1.6.3 release but is not in the latest commits--meaning this issue will still occur when using the latest `pip install python_ta` version, but it has already been fixed and should not happen in the next release.

**Comment by david-yz-liu** [comment]
Ah perfect, thanks for looking into this @ckatsube!

**Comment by MichaelLiut** [comment]
Thanks for the information and for looking into this @ckatsube! :)
