### ISSUE TITLE
Changing if/else error for readability

### ISSUE THREAD

**Issue by kleenkanteen** [pyta-uoft/pyta#650]
For pyta, it flags this piece of code as an error, giving the error "R1705 (no-else-return)". Also this error isn't in the [documentation ](https://www.cs.toronto.edu/~david/pyta/):

```
a = True  
if a:  
       return "Happy"  
else:  
      return "Sad"
```

to fix it, pyta requires me to change it to:

```
a = True
if a:
       return "Happy"
return "Sad"
```

I think that the first block of code should not raise an error because of readability. The first is noticeably clearer to read, showing that there are only 2 outcomes. The second does save a line of code, but I think the readability of the first is more beneficial.

Pyta right now basically eliminates you from using a simple if else statement that has 2 outcomes. 

For a larger exmaple, imagine if the code inside the if and else blocks were 10 lines each. If I wrote it the way I did it in the first way, with a return at the end of each, it would be easy to read as both blocks of code would be indented under a if or else statement. The relationship with the variable `a` is clear.

If I did it the second way, then the second 10 lines of code that were in the else statement is now unindented and by itself. It is harder to see the relationship between the 10 lines with the variable `a`.

So I think this error should be reconsidered.

**Comment by david-yz-liu** [comment]
You read my mind, I was going to disable this one tonight anyway, so good timing. :)

It's a check from pylint, not python_ta itself, so we can't remove it entirely, but it's disabled by default now.

**Comment by kleenkanteen** [comment]
It seems like it still happens. I have the latest version downloaded, 1.6.2b1. Looking at the code my classmates write, it's interesting how it's instilling a fundamental and bad coding style for 200 people.
