### ISSUE TITLE
User question: Error message: "Instance variable should be annotated in class body"

### ISSUE THREAD

**Issue by s8sun** [pyta-uoft/pyta#659]
When I declare a class: 
```
def class boo: 
"""
some proper docstring
"""
    def __init__(someFile):
        self._list = []
        self.file = someFile


   def foo(self):
   #some class method

```

I receive an error message that says "Instance variable should be annotated in class body" on the line I declare variable self._list = []. What is the preferred format that pyta want? What is the annotation it is asking for?

**Comment by david-yz-liu** [comment]
Ah, yes PyTA is checking for type annotations for the attributes, e.g.:

```python
def class boo: 
    """
    some proper docstring
    """
    _list: list
    file: str

    def __init__(someFile):
        self._list = []
        self.file = someFile
```
