### ISSUE TITLE
Document configuration

### ISSUE THREAD

**Issue by alexmojaki** [pyta-uoft/pyta#669]
It took me quite a bit of digging through source code to figure out how to configure a reporter, i.e. `python_ta.check_errors(config={"pyta-reporter": "PlainReporter"})`. Is configuration documented somewhere? The only documentation pages I can find are:

- https://www.cs.toronto.edu/~david/pyta/
- https://www.cs.toronto.edu/~david/pyta/quick_start.html

Are there more?

**Comment by david-yz-liu** [comment]
Sadly there's no documentation for reporters (or other PythonTA options) right now. Leaving this open as work for the future.
