### ISSUE TITLE
Raw data API?

### ISSUE THREAD

**Issue by alexmojaki** [pyta-uoft/pyta#670]
This project looks great, and I'm interested in using it for my project https://github.com/alexmojaki/futurecoder

However I don't want anything formatted or displayed for me. I want to access the raw data about coding errors produced by checkers. Is there a good way to do that?

One possibility is to to just load the PyTA custom checkers and then run pylint myself which I believe has such an API. But I imagine I'd be missing out on other features of PyTA, although I'm not exactly clear what. These are the things I can see that PyTA adds to pylint:

- Custom checkers
- Beginner friendly interface, output format, and error messages
- Contract checking

I don't need the last two. What else is there? Am I better of just using pylint?

**Comment by david-yz-liu** [comment]
Hi @alexmojaki! Sorry for the lateness on this reply, I'm currently not checking in very regularly on this project. futurecoder looks like a very cool project!

The short answer is you're probably better off using pylint, which is much better supported. (And to be clear, I'm a huge fan of that project!) You're welcome to adapt the custom PyTA checkers into your own project as well.

The longer answer is that PyTA doesn't exactly support what you describe, but you can adapt https://github.com/pyta-uoft/pyta/blob/master/python_ta/reporters/position_reporter.py to suit your needs. The `PositionReporter` subclass in that file has an attribute `_output` that we serialize to JSON.

**Comment by alexmojaki** [comment]
Ok, thanks!
