### ISSUE TITLE
We have a little Ownership problem here!

### ISSUE THREAD

**Issue by matin1099** [pyta-uoft/pyta#801]
Dear Sir or Madam

   I have started to develop a personal project related to teaching Python language and unfortunately this project is also called 'PyTA' that stands for '_PY_thon for _T_eaching _A_ssistances' .

   The ultimate goal of this project is to prepare summary notes and simple to hard exercises to help university teaching instructors.
All resources of this project are free resources and will be published in English and Persian under the **GNU/GPL** license.

   Given the background of your **project** and its **publication**, I consider it your right to inform you of this i**nadvertent mistake** and to know your opinion on solving this problem.

My personal suggestion is that, since the working fields of both of us _do not interfere_ with each other, I should continue my project with the same name and publish with the same name.
Of course, **in the  "Readme.me" file, I will resolve the misunderstanding** and put your project link in that section.

And my second suggestion, which I do not want to make because of the problems it will have for me, is to rename my project. Because the project is still in alpha release mode and its repository is not yet public, the rename option is also on the table.
But as I said, I do not want it and I will introduce it as my last solution. The reason for this is that **costs have been incurred for this name, some of which are irreparable.**

**I would like to know your opinion in this regard and solve this problem with your cooperation.**

**Sincerely**
**Matin Nosraty**

**Comment by david-yz-liu** [comment]
Thank you for the information. I'm fine with your project continuing to use the name "PyTA".
