### ISSUE TITLE
Contract checker bug?

### ISSUE THREAD

**Issue by amanjitsk** [pyta-uoft/pyta#831]
Hi, 
I was testing out the `check_all_contracts` function on a basic example as follows:

```python
def f(a: int, b: int) -> float:
    """Return the result when dividing a by b.

    >>> f(10, 5)
    2.0
    """
    return a // b


if __name__ == "__main__":
    import python_ta.contracts
    python_ta.contracts.check_all_contracts()
    print(type(f(10, 5)))
    print(python_ta.__version__)
```
running this gives the output

```shell
<class 'int'>
2.2.0
```

I would think this should get caught as a violation of the type contract because the return type is `int`, but the type annotation indicates `float`. But this does not get caught as an `AssertionError`. Am I overlooking something super basic here ? The python version is `3.10.4`.

Thanks,
Amanjit

**Comment by david-yz-liu** [comment]
Good question, it looks like the type-checking library we're using does not consider this an error: https://github.com/agronholm/typeguard/issues/224.

I'll leave this issue open since I think it would be good to be stricter in PythonTA.

**Comment by amanjitsk** [comment]
Ah ok I see. Thanks for the quick response. Yeah I agree we should probably have a stricter check (especially when using this for first-year courses).
