### ISSUE TITLE
Please delete this unnecessary issue. I just found the solution for it

### ISSUE THREAD

**Issue by AnnabellBrocker** [pyta-uoft/pyta#910]

**Comment by david-yz-liu** [comment]
Hello! Thanks for asking---we're still working on our documentation for the configuration for PythonTA. You can see the default PythonTA configuration at https://github.com/pyta-uoft/pyta/blob/master/python_ta/config/.pylintrc, and provide your own `.pylintrc` file. You can also pass these options in a dictionary as the `config` argument in `python_ta.check_all`, e.g.

```python
python_ta.check_all(config={
  'extra-imports': ['math', 'my_other_module']
})
```

Hope that helps!
