### ISSUE TITLE
Error parsing configuration file 

### ISSUE THREAD

**Issue by utmandrew** [pyta-uoft/pyta#916]
When providing a configuration file using check_all, python_ta throws a parsing error. The configuration file provided does not appear to matter; it fails for one that worked in previous versions as well as the one in the repository. python_ta works without error is no config file is provided.

`# Confirming python_ta and dependencies
(pcrsenv) peters43:/Users/peters43/temp$ pip3 install python_ta
Requirement already satisfied: python_ta in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (2.5.0)
Requirement already satisfied: astroid~=2.12.13 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (2.12.14)
Requirement already satisfied: pycodestyle~=2.10.0 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (2.10.0)
Requirement already satisfied: pylint~=2.15.8 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (2.15.10)
Requirement already satisfied: tabulate~=0.9.0 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (0.9.0)
Requirement already satisfied: colorama~=0.4.6 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (0.4.6)
Requirement already satisfied: six in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (1.15.0)
Requirement already satisfied: jinja2~=3.1.2 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (3.1.2)
Requirement already satisfied: pygments~=2.14.0 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (2.14.0)
Requirement already satisfied: wrapt<2,>=1.15.0 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (1.15.0)
Requirement already satisfied: typeguard<3,>=2.13.3 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (2.13.3)
Requirement already satisfied: requests~=2.28.0 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (2.28.2)
Requirement already satisfied: click<9,>=8.0.1 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (8.0.1)
Requirement already satisfied: toml~=0.10.2 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from python_ta) (0.10.2)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from astroid~=2.12.13->python_ta) (1.4.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from jinja2~=3.1.2->python_ta) (2.1.3)
Requirement already satisfied: platformdirs>=2.2.0 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from pylint~=2.15.8->python_ta) (2.2.0)
Requirement already satisfied: isort<6,>=4.2.5 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from pylint~=2.15.8->python_ta) (4.3.21)
Requirement already satisfied: mccabe<0.8,>=0.6 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from pylint~=2.15.8->python_ta) (0.6.1)
Requirement already satisfied: tomlkit>=0.10.1 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from pylint~=2.15.8->python_ta) (0.11.8)
Requirement already satisfied: dill>=0.3.6 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from pylint~=2.15.8->python_ta) (0.3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from requests~=2.28.0->python_ta) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from requests~=2.28.0->python_ta) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from requests~=2.28.0->python_ta) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages (from requests~=2.28.0->python_ta) (2020.6.20)

# Confirming python version, demonstrating error encountered on check_all
(pcrsenv) peters43:/Users/peters43/temp$ python3
Python 3.11.4 (main, Jun  7 2023, 00:34:23) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_ta
>>> python_ta.check_all("148_responded.py", config="/Users/peters43/projects/pcrs/utmandrew/pcrs/languages/python/pyta/pyta.config")
[ERROR] Unexpected error encountered! Please report this to your instructor (and attach the code that caused the error).
[ERROR] Error message: "list index out of range"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/__init__.py", line 79, in check_all
    return _check(module_name=module_name, level="all", local_config=config, output=output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/__init__.py", line 172, in _check
    raise e
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/__init__.py", line 127, in _check
    linter = reset_linter(config=local_config, file_linted=file_py)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/__init__.py", line 319, in reset_linter
    _load_config(linter, config)
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/__init__.py", line 192, in _load_config
    _config_initialization(linter, args_list=[], config_file=config_location)
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/pylint/config/config_initialization.py", line 103, in _config_initialization
    linter._emit_stashed_messages()
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 1356, in _emit_stashed_messages
    self.add_message(
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/patches/messages.py", line 27, in new_add_message
    self.reporter.handle_node(msg_info, node)
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/reporters/core.py", line 115, in handle_node
    snippet = self._build_snippet(msg, node)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/reporters/core.py", line 151, in _build_snippet
    for lineno, slice_, line_type, text in render_message(msg, node, self.source_lines):
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/reporters/node_printers.py", line 10, in render_message
    yield from renderer(msg, node, source_lines)
  File "/Users/peters43/.virtualenvs/pcrsenv/lib/python3.11/site-packages/python_ta/reporters/node_printers.py", line 47, in render_generic
    yield (line, slice(None, None), LineType.ERROR, source_lines[line - 1])
                                                    ~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
>>> quit()

# Confirming that configuration file is the one from the newest release
(pcrsenv) peters43:/Users/peters43/temp$ cat /Users/peters43/projects/pcrs/utmandrew/pcrs/languages/python/pyta/pyta.config 
[CUSTOM PYTA OPTIONS]

# Make sure to register custom options tuple first in `python_ta/__init__.py`
# ===========================================================
# Default max amount of messages for reporter to display.
pyta-number-of-messages = 5

# (DEPRECATED: Use output-format option below.) Set the [REPORTS] output-format option instead.
# pyta-reporter = HTMLReporter

# Set the location of the template for HTMLreporter.
pyta-template-file = template.html.jinja

#Set whether you wish to opt-in to anonymous data collection of errors reported when you run PyTA.
pyta-error-permission = no

#Set whether you wish to opt-in to anonymous data collection of the files you run PyTA on.
pyta-file-permission = no

# Server address for data submission participation.
pyta-server-address = http://127.0.0.1:5000

# Path to messages_config toml file
# messages-config-path = messages.toml

[REPORTS]
# The type of reporter to use to display results. Available PyTA classes are
# PlainReporter, ColorReporter, HTMLReporter, JSONReporter.
# Replaces the pyta-reporter option.
output-format = python_ta.reporters.HTMLReporter

[ELIF]

# Set maximum allowed if nesting.
max-nested-blocks = 3

[FORMAT]

# Set the maximum line length. The maximum line length in pep8 is 80 characters.
max-line-length = 80

# Regexp for a line that is allowed to be longer than the limit.
ignore-long-lines = ^\s*((# )?<?https?://\S+>?)|(>>>.*)$

[FORBIDDEN IMPORT]

# Set the whitelist of modules that are allowed to be imported
allowed-import-modules = dataclasses, doctest, unittest, hypothesis, pytest, python_ta, python_ta.contracts,
                         timeit, typing, __future__
extra-imports =
[FORBIDDEN IO]

# Comma-separated names of functions that are allowed to contain IO actions
allowed-io =

[MESSAGES CONTROL]

# Disable the message, report, category or checker with the given id(s).
disable=
    E0100, E0105, E0106, E0110, E0112, E0113, E0114, E0115, E0116, E0117, E0118,
    E0236, E0237, E0238, E0240, E0242, E0243, E0244, E0305, E0308, E0309, E0310, E0311, E0312, E0313,
    E0402,
    E0603, E0604, E0605,
    E0703, W0707,
    E1124, E1125, E1132, E1139, E1142,
    E1200, E1201, E1205, E1206,
    E1300, E1301, E1302, E1303, E1304,
    W1406,
    E1507, E1519,
    E1700, E1701,
    E9900,
    W0120, W0131, W0150, W0177,
    W0213, W0235, W0236, W0238, W0244, W0246,
    W0601, W0602, W0614, W0640,
    W1113, W1115,
    W1300, W1301, W1302, W1306, W1307,
    W1502, W1503, W1505, W1506, W1507, W1508, W1509, W1510, W1511, W1512, W1513, W1514, W1518,
    C0105, C0131, C0132,
    C0200, C0202, C0203, C0204, C0205, C0206, C0207, C0208,
    C0327, C0328,
    R0202, R0203, R0206,
    R0901, R0903, R0904, R0911,
    R1703, R1705, R1706, R1708, R1709, R1711, R1717, R1718, R1719, R1720, R1722, R1723, R1724,
    R1728, R1729, R1730, R1731,
    C1803,
    F0202,
    W0402, W0407,
    W0603,
    W1201, W1202,
    I0023,
    I1101,
    lambda-expressions,
    similarities,
    spelling,
    threading,
    unnecessary-dunder-call,
    unsupported_version,
    E2502, E2510, E2511, E2512, E2513, E2514, E2515,
    missing-timeout, positional-only-arguments-expected


# Enable single-letter identifiers
function-rgx = (([a-z][a-z0-9_]{0,30})|(_[a-z0-9_]*))$
variable-rgx = (([a-z][a-z0-9_]{0,30})|(_[a-z0-9_]*)|([A-Z_][A-Z0-9_]*))$
const-rgx    = (([A-Z_][A-Z0-9_]*)|(__.*__))$
attr-rgx     = (([a-z][a-z0-9_]{0,30})|(_[a-z0-9_]*))$
argument-rgx = (([a-z][a-z0-9_]{0,30})|(_[a-z0-9_]*))$
class-rgx    = (([A-Z][a-zA-Z0-9]{0,30})|(_[A-Z][a-zA-Z0-9]*))$
method-rgx   = (([a-z][a-z0-9_]{0,30})|(_[a-z0-9_]*))$
class-attribute-rgx = ([A-Za-z_][A-Za-z0-9_]{0,30}|(__.*__))$

[PYCODESTYLE]
# Ignored pycodestyle checks
pycodestyle-ignore =
    E111,  # pylint W0311
    E114,  # pylint W0311
    E117,  # pylint W0311
    E401,  # pylint C0410
    E402,  # pylint C0413
    E501,  # pylint C0301
    E701,  # pylint C0321
    E702,  # pylint C0321
    E703,  # pylint W0301
    E711,  # pylint C0121
    E712,  # pylint C0121
    E722,  # pylint W0702
    W291,  # pylint C0303
    W292,  # pylint C0304
    W293,  # pylint C0303
    W391,  # pylint C0305
    W503   # this one just conflicts with pycodestyle W504`

**Comment by david-yz-liu** [comment]
@utmandrew I'm sorry, I gave you the wrong link (config file on master rather than 2.5.0). Can you please try: https://raw.githubusercontent.com/pyta-uoft/pyta/v2.5.0/python_ta/config/.pylintrc

(As an aside, there's a bug in reporting the actual error in parsing the configuration file that we'll fix soon.)

**Comment by utmandrew** [comment]
The new config link works well. Thank you!
