### ISSUE TITLE
PythonTA considers _ as an invalid name for variables

### ISSUE THREAD

**Issue by klokailo** [pyta-uoft/pyta#955]
Common practice in python and other programming languages is to use `_` as the name of an unused variable (usually occurs when you do not need to reference a variable created in a loop). Instead of respecting this common practice, PythonTA gives a warning about incorrect variable naming conventions.

**Comment by david-yz-liu** [comment]
Hello,

Thanks for reporting this, we have resolved this in our new release (2.6.2)!
