### ISSUE TITLE
Make `check_contracts` allow passing integers in for float types

### ISSUE THREAD

**Issue by ChristopherLi05** [pyta-uoft/pyta#958]
```python
from python_ta.contracts import check_contracts

@check_contracts
def foo(a: float):
    print(a)

foo(1)
```

Running this gives the error `AssertionError: foo argument 1 did not match type annotation for parameter a: float`.

**Comment by ChristopherLi05** [comment]
This was a minor annoyance in this week's `prep3` exercise in creating test cases as you would need to put a `.0` (or just a `.` which is just ugly) after all the salaries instead of just being able to put the number in.

**Comment by ch-iv** [comment]
That is the intended behaviour. Making integers pass a float annotation check would be counter productive to what python-ta is trying to do - enforce the type annotation. Instead you should indicate that your function takes a float or an int by doing:
```python
def foo(a: float | int):
    print(a)
```

**Comment by ChristopherLi05** [comment]
If you run this code, python-ta does not throw an error:

```

**Comment by ChristopherLi05** [comment]
I suggest just letting typeguard do its own thing and making the user add a precondition like `- type(arg) is float` or `isinstance(arg, float)` if the typing actually matters.
