### ISSUE TITLE
toronto.edu website has outdated PyTA docs

### ISSUE THREAD

**Issue by paulschreiber** [pyta-uoft/pyta#978]
On this page:
https://www.cs.toronto.edu/~david/pyta/cfg/

There is older code:
```python
    import python_ta.cfg

    python_ta.cfg.generate_cfg()
```

The repo has the updated docs:
https://github.com/pyta-uoft/pyta/blob/master/docs/cfg/index.md

```python
    import python_ta.cfg.cfg_generator as cfg_generator

    cfg_generator.generate_cfg()
```

**Comment by david-yz-liu** [comment]
Thank you @paulschreiber! I must have missed updating the website. I've just updated it now
